spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/user_db
    driver-class-name: org.mariadb.jdbc.Driver
    username: 'root'
    password: '0000'
  jpa:
    database-platform: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate